---
title: "SlopeSeaMapPlots"
author: "Chrissy Hernandez"
date: "8/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data QA steps Aug 5 2020

```{r}
# read in the 6B3Z data and pull out the rows with bluefin data:
zoopBongo<- read.csv('data/HB1603_GU1608_IchData_7Nov2019.csv')
head(zoopBongo)
tunaBongo<- zoopBongo[zoopBongo$TAXA_NAME=="Thunnus thynnus",]
head(tunaBongo)

# read in Dave's ID and length data to compare:
tunaDave<- read.csv('data/2016MeasuredFish_CMH200622.csv')
head(tunaDave)

# pull out the columns of tunaBongo that we want:
tunaBongo_tocompare<- tunaBongo[,c("CRUISE_NAME", "GEAR", "STATION", "COUNT_AT_LENGTH", "LENGTH")]
head(tunaBongo_tocompare)

# summarize tunaDave:
tunaDave$LengthRounded<- round(tunaDave$Length, digits=1)
tunaDave_summary<- aggregate(Fish~Cruise+Gear+Station+LengthRounded, data=tunaDave, FUN='length')
names(tunaDave_summary)<- c("CRUISE_NAME", "GEAR", "STATION", "LENGTH", "DaveCount")

# merge tunaDave and tunaBongo_tocompare to properly compare
comparison<- merge(tunaDave_summary, tunaBongo_tocompare, all.x = T, all.y = T)
write.csv(comparison, file='results/tunacounts_check_2020.08.05.csv')

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
